<template>
  <v-dialog
    v-model="dialog"
    fullscreen
    hide-overlay
    transition="dialog-bottom-transition"
  >
    <template #activator="{ on, attrs }">
      <v-btn
        color="blue"
        text
        v-bind="attrs"
        v-on="on"
      >
        회원가입하기
      </v-btn>
    </template>
    <v-card>
      <v-toolbar
        color="white"
      >
        <v-toolbar-title>회원가입</v-toolbar-title>
        <v-spacer />
        <v-toolbar-items>
          <v-btn
            icon
            @click="dialog = false"
          >
            <v-icon>mdi-close</v-icon>
          </v-btn>
        </v-toolbar-items>
      </v-toolbar>
      <v-card-text>
        <v-form>
          <v-row
            align="center"
            class="mt-1"
          >
            <v-col
              cols="3"
              sm="5"
              md="5"
              lg="3"
              xl="3"
            >
              <span>스토어 이미지</span>
            </v-col>
            <v-col
              cols="3"
              sm="3"
              md="2"
              lg="2"
              xl="2"
              class="ml-0 mr-6"
            >
              <v-avatar
                size="80"
              >
                <img
                  alt="John"
                  src="https://cdn.vuetifyjs.com/images/john.jpg"
                >
              </v-avatar>
            </v-col>
            <v-col
              cols="3"
              sm="3"
              md="3"
              lg="3"
              xl="3"
            >
              <input
                ref="imageInput"
                hidden
                multiple
                type="file"
                @change="onChangeImages"
              >
              <v-btn
                class="pa-0 ma-0"
                color="primary"
                outlined
                rounded
                type="button"
                @click="onClickImgUpload"
              >
                <label>사진 업로드</label>
                <v-icon right>
                  mdi-camera
                </v-icon>
              </v-btn>
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>아이디</span>
            </v-col>
            <v-col
              cols="5"
              sm="6"
              md="3"
              xl="3"
              lg="3"
            >
              <v-text-field
                clearable
                label="아이디를 입력해주세요"
                solo
                hide-details
              />
            </v-col>
            <v-col
              cols="1"
              sm="1"
              md="1"
              lg="1"
              xl="1"
            >
              <v-btn class="pa-0 ma-0">
                중복확인
              </v-btn>
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>비밀번호</span>
            </v-col>
            <v-col
              cols="8"
              sm="8"
              md="4"
              xl="4"
              lg="4"
            >
              <v-text-field
                clearable
                label="비밀번호를 입력해주세요"
                solo
                hide-details
              />
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>비밀번호 확인</span>
            </v-col>
            <v-col
              cols="8"
              sm="8"
              md="4"
              lg="4"
              xl="4"
            >
              <v-text-field
                clearable
                label="비밀번호 확인"
                solo
                hide-details
              />
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              xl="2"
              lg="2"
            >
              <span>이메일</span>
            </v-col>
            <v-col
              cols="8"
              sm="8"
              md="4"
              lg="4"
              xl="4"
            >
              <v-text-field
                class="ma-0 pa-0"
                label="이메일을 입력해주세요"
                clearable
                solo
                hide-details
              />
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>닉네임</span>
            </v-col>
            <v-col
              cols="8"
              sm="8"
              md="4"
              lg="4"
              xl="4"
            >
              <v-text-field
                clearable
                label="닉네임 입력해주세요"
                solo
                hide-details
              />
            </v-col>
            <v-col
              cols="1"
              sm="1"
              md="1"
              lg="1"
              xl="1"
            >
              <v-btn class="pa-0 ma-0">
                중복확인
              </v-btn>
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>전화번호</span>
            </v-col>
            <v-col
              cols="8"
              sm="8"
              md="4"
              lg="4"
              xl="4"
            >
              <v-text-field
                clearable
                label="전화번호를 입력해주세요"
                solo
                hide-details
              />
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>우편번호</span>
            </v-col>
            <v-col
              cols="4"
              sm="6"
              md="3"
              xl="3"
              lg="3"
            >
              <v-text-field
                clearable
                label="우편번호"
                solo
                hide-details
              />
            </v-col>
            <v-col
              cols="1"
              sm="1"
              md="1"
              lg="1"
              xl="1"
            >
              <v-btn>주소검색</v-btn>
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="3"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>주소</span>
            </v-col>
            <v-col
              cols="8"
              sm="8"
              md="4"
              xl="4"
              lg="4"
            >
              <v-text-field
                clearable
                label="주소를 입력해주세요"
                solo
                hide-details
              />
            </v-col>
          </v-row>
          <v-row
            align="center"
          >
            <v-col
              cols="4"
              sm="4"
              md="4"
              lg="2"
              xl="2"
            >
              <span>상세주소</span>
            </v-col>
            <v-col
              cols="8"
              sm="8"
              md="4"
              lg="4"
              xl="4"
            >
              <v-text-field
                clearable
                label="상세주소를 입력해주세요"
                solo
                hide-details
              />
            </v-col>
          </v-row>
        </v-form>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn
          class="white--text"
          color="blue darken-1"
          @click="dialog = true"
        >
          가입
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>
<script>
export default {
  name: "Signup",
  data: () => ({
    dialog: false
  }),
  methods: {
    onClickImgUpload () {
      this.$refs.imageInput.click();
    },
    onChangeImages (e) {
      console.log(e.target.files);
      const imgFormData = new FormData();
      [].forEach.call(e.target.files, (f) => {
        imgFormData.append('img', f);
      });
    }
  }
}
</script>

<style scoped>

</style>
